/**
 * Created by shine on 29/6/2017.
 */
export const SELECT_WORK_ADDRESS = 'SELECT_WORK_ADDRESS';
export const REMOVE_WORK_ADDRESS = 'REMOVE_WORK_ADDRESS';
export const SELECT_HOME_ADDRESS = 'SELECT_HOME_ADDRESS';
export const REMOVE_HOME_ADDRESS = 'REMOVE_HOME_ADDRESS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const FETCH_ROUTE_FROM_SOURCE = 'FETCH_ROUTE_FROM_SOURCE';
export const FETCH_ROUTE_FROM_DESTINATION = 'FETCH_ROUTE_TO_DESTINATION';

export const SHOW_MODAL = 'SHOW_MODAL';
export const MODAL_SELECT_BASE_ROUTE = 'MODAL_SELECT_BASE_ROUTE';